receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
  batch:

exporters:
  # Traces -> Splunk Observability Cloud APM.
  otlphttp/splunk:
    traces_endpoint: ${env:SPLUNK_INGEST_URL}/v2/trace/otlp
    headers:
      X-SF-Token: ${env:SPLUNK_ACCESS_TOKEN}

  # Metrics -> Splunk Observability Cloud.
  signalfx:
    access_token: ${env:SPLUNK_ACCESS_TOKEN}
    api_url: ${env:SPLUNK_API_URL}
    ingest_url: ${env:SPLUNK_INGEST_URL}
    sync_host_metadata: false

  # Logs -> Splunk Observability Cloud HEC endpoint.
  splunk_hec/logs:
    token: ${env:SPLUNK_ACCESS_TOKEN}
    endpoint: ${env:SPLUNK_HEC_URL}
    source: otel
    sourcetype: otel
    profiling_data_enabled: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/splunk]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [signalfx]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [splunk_hec/logs]
